"""add watches

Revision ID: 4a1658f1f280
Revises: 57040e9deb51
Create Date: 2026-10-07 23:37:27.814158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a1658f1f280'
down_revision: Union[str, Sequence[str], None] = '57040e9deb51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('product', 'style_code', 'keyword', name='watchtype', native_enum=False), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(length=500), nullable=True),
    sa.Column('keywords_pos', sa.JSON(), nullable=False),
    sa.Column('keywords_neg', sa.JSON(), nullable=False),
    sa.Column('store_ids', sa.JSON(), nullable=True),
    sa.Column('sizes', sa.JSON(), nullable=True),
    sa.Column('event_types', sa.JSON(), nullable=False),
    sa.Column('max_price_cents', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_watches_product_id_products')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_watches_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_watches'))
    )
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_watches_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watches_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watches_user_id'))
        batch_op.drop_index(batch_op.f('ix_watches_product_id'))

    op.drop_table('watches')
    # ### end Alembic commands ###
